
publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: main
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: public/assets/images
public_folder: /assets/images

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Created Date', name: 'createdAt', widget: 'datetime', format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Image', name: 'image', widget: 'string', required: true }
      - { label: 'SubImage', name: 'subImage', widget: 'string', required: true }
      - { label: 'Id', name: 'id', widget: 'number', required: true }
      - {
          label: 'Blog Category',
          name: 'category',
          widget: 'select',
          default: 'mens-clothing',
          options: [{ label: 'Mens-clothing', value: 'mens-clothing' }, { label: 'Men', value: 'men' }, { label: 'Women', value: 'women' }],
        }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  - name: 'hall-of-fame'
    label: 'Hall-Of-Fame'
    folder: 'content/hall-of-fame'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Id', name: 'id', widget: 'number', required: true }
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Image', name: 'image', widget: 'string', required: true }
      - { label: 'SubImage', name: 'subImage', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  - name: 'line-stories'
    label: 'Line-Stories'
    folder: 'content/line-stories'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Id', name: 'id', widget: 'number', required: true }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Video', name: 'video', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  - name: 'students-projects'
    label: 'Students-Projects'
    folder: 'content/students-projects'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Id', name: 'id', widget: 'number', required: true }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Video', name: 'video', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  - name: 'tes1'
    label: 'Tes1'
    folder: 'content/tes/1'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Id', name: 'id', widget: 'number', required: true }
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Image', name: 'image', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
  - name: 'tes2'
    label: 'Tes2'
    folder: 'content/tes/2'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Id', name: 'id', widget: 'number', required: true }
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Image', name: 'image', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
  - name: 'tes3'
    label: 'Tes3'
    folder: 'content/tes/3'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Id', name: 'id', widget: 'number', required: true }
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Image', name: 'image', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
  - name: 'courses'
    label: 'Courses'
    folder: 'content/courses'
    label_singular: 'Course'
    folder: 'content/courses'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'courses/{{slug}}'
    fields:
      - {
          label: 'Courses Category',
          name: 'category',
          widget: 'select',
          default: 'mens-clothing',
          options: [{ label: 'Mens-clothing', value: 'mens-clothing' }, { label: 'Men', value: 'men' }, { label: 'Women', value: 'women' }],
        }
      - { label: 'Created Date', name: 'createdAt', widget: 'datetime', format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Image', name: 'image', widget: 'string', required: true }
      - { label: 'SubImage', name: 'subImage', widget: 'string', required: true }
      - { label: 'Id', name: 'id', widget: 'number', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
      - {
          label: 'Videos',
          name: 'videos',
          widget: 'list',
          required: true,
          collapsed: false,
          fields: 
            - {label: 'Video', name: 'video', widget: 'string'}
            - {label: 'Title', name: 'title', widget: 'string'}
        }
        # English
  - name: 'blogen'
    label: 'Blogen'
    folder: 'content/en-us/blog'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Created Date', name: 'createdAt', widget: 'datetime', format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Image', name: 'image', widget: 'string', required: true }
      - { label: 'SubImage', name: 'subImage', widget: 'string', required: true }
      - { label: 'Id', name: 'id', widget: 'number', required: true }
      - {
          label: 'Blog Category',
          name: 'category',
          widget: 'select',
          default: 'mens-clothing',
          options: [{ label: 'Mens-clothing', value: 'mens-clothing' }, { label: 'Men', value: 'men' }, { label: 'Women', value: 'women' }],
        }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  - name: 'hall-of-fameen'
    label: 'Hall-Of-Fameen'
    folder: 'content/en-us/hall-of-fame'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Id', name: 'id', widget: 'number', required: true }
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Image', name: 'image', widget: 'string', required: true }
      - { label: 'SubImage', name: 'subImage', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  - name: 'line-storiesen'
    label: 'Line-Storiesen'
    folder: 'content/en-us/line-stories'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Id', name: 'id', widget: 'number', required: true }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Video', name: 'video', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  - name: 'students-projectsen'
    label: 'Students-Projectsen'
    folder: 'content/en-us/students-projects'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Id', name: 'id', widget: 'number', required: true }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Video', name: 'video', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  - name: 'tes1en'
    label: 'Tes1en'
    folder: 'content/en-us/tes/1'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Id', name: 'id', widget: 'number', required: true }
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Image', name: 'image', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
  - name: 'tes2en'
    label: 'Tes2en'
    folder: 'content/en-us/tes/2'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Id', name: 'id', widget: 'number', required: true }
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Image', name: 'image', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
  - name: 'tes3en'
    label: 'Tes3en'
    folder: 'content/en-us/tes/3'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Id', name: 'id', widget: 'number', required: true }
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Image', name: 'image', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
  - name: 'coursesen'
    label: 'Coursesen'
    folder: 'content/en-us/courses'
    label_singular: 'Course'
    folder: 'content/courses'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'courses/{{slug}}'
    fields:
      - {
          label: 'Courses Category',
          name: 'category',
          widget: 'select',
          default: 'mens-clothing',
          options: [{ label: 'Mens-clothing', value: 'mens-clothing' }, { label: 'Men', value: 'men' }, { label: 'Women', value: 'women' }],
        }
      - { label: 'Created Date', name: 'createdAt', widget: 'datetime', format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Image', name: 'image', widget: 'string', required: true }
      - { label: 'SubImage', name: 'subImage', widget: 'string', required: true }
      - { label: 'Id', name: 'id', widget: 'number', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
      - {
          label: 'Videos',
          name: 'videos',
          widget: 'list',
          required: true,
          summary: '{{fields.video}}',
          fields: 
            - { label: 'Video', name: 'video', widget: 'string' }
            - { label: 'Title', name: 'title', widget: 'string' }
        }
